# Common host configuration.
{ config, pkgs, lib, ... }:
{
  imports = [ 
    ../users/root/default.nix # Root User Options
    ../hardware-configuration.nix # Autogenerated
  ];
  boot.loader.timeout = 1; # Set timeout to 1 for faster boot speeds.
  boot.kernelModules = [
    "tcp_bbr"
    "bfq"
  ];
  boot.kernel.sysctl = {
  "net.core.default_qdisc"             = "fq";
  "net.ipv4.tcp_congestion_control"    = "bbr";
  "net.ipv4.tcp_slow_start_after_idle" = "0"; # Should help to improve performance in some cases.
  };

  console.useXkbConfig = true; # Use keymap from xserver.

  environment.systemPackages = with pkgs; [
  # applications/editors
  vim # The most popular clone of the VI editor
  # applications/version-management
  gitAndTools.gitFull # Distributed version control system
  # tools/networking
  bwm_ng # A small and simple console-based live network and disk io bandwidth monitor
  curlFull # A command line tool for transferring files with URL syntax
  #inetutils # Collection of common network programs
  tftp-hpa # TFTP tools - a lot of fixes on top of BSD TFTP
  wget # Tool for retrieving files using HTTP, HTTPS, and FTP
  # tools/package-management
  appimagekit # A tool to package desktop applications as AppImages
  # tools/security
  mkpasswd # Overfeatured front-end to crypt, from the Debian whois package
  # tools/system
  htop # An interactive process viewer for Linux
  hwinfo # Hardware detection tool from openSUSE
  nq # Unix command line queue utility
  pciutils # A collection of programs for inspecting and manipulating configuration of PCI devices
  plan9port # Plan 9 from User Space
  ];

  hardware.ksm.enable = true; # Kernel Same-Page Merging

  nix.autoOptimiseStore = true;
  nix.gc.automatic = true;
  nix.gc.options = "--delete-older-than 30d";
  nix.trustedUsers = [ "root" "@wheel" ];

  powerManagement.enable = lib.mkDefault false;

  programs.dconf.enable = true;
  programs.gnupg.agent = { enable = true; enableSSHSupport = true; };
  programs.mosh.enable = true;
  programs.nano.syntaxHighlight = true;
  programs.tmux.enable = true;
  programs.tmux.keyMode = "vi";

  security.hideProcessInformation = true;

  services.fail2ban.enable = true;
  services.flatpak.enable = true;
  services.fstrim.enable = true;
  services.logind.extraConfig = ''KillUserProcesses=yes
    HandlePowerKey=ignore'';
  services.openssh.enable = true;
  services.timesyncd.enable = true;

  system.autoUpgrade.enable = true;
  system.stateVersion = "19.09"; # Check release notes before changing this. *insert scary warning here*

  systemd.extraConfig = "DefaultLimitNOFILE=1048576"; # Set limits for Esync: https://github.com/lutris/lutris/wiki/How-to:-Esync

  time.timeZone = "America/Los_Angeles"; # Set this to your local timezone: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
}
